import os

from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, sessionmaker

# Load environment variables from a .env file. This allows the application to access configuration settings, such as the database URL, from the environment.
load_dotenv()
Database_URL = os.getenv("DATABASE_URL")

# Check if the DATABASE_URL environment variable is set. If it is not set, raise a ValueError to indicate that the application cannot proceed without a valid database URL.
if not Database_URL:
    raise ValueError("DATABASE_URL environment variable is not set.")

# Create a SQLAlchemy engine instance using the specified database URL. The echo parameter is set to True, which enables logging of all SQL statements generated by SQLAlchemy, useful for debugging and development purposes.
engine = create_engine(
    Database_URL,
    echo=True,
)

# Define a base class for declarative class definitions using SQLAlchemy's DeclarativeBase. This base class will be used to define the database models (tables) in the application.
SessionLocal = sessionmaker(
    bind=engine,
    autoFlush=False,
    autocommit=False,
)


# Define a base class for declarative class definitions using SQLAlchemy's DeclarativeBase. This base class will be used to define the database models (tables) in the application.
class Base(DeclarativeBase):
    """Base class for declarative class definitions."""
    pass

# Define a dependency function to get a database session. This function creates a new session using the SessionLocal factory, yields it for use in the application, and ensures that the session is closed after use to prevent resource leaks.
def get_db():
    """Dependency function to get a database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()