from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, sessionmaker


# Database URL for connecting to the PostgreSQL database
Database_URL = (
    "postgresql+psycopg2://"
    "incident_user:incident_password"
    "@localhost:5432/incident_db"
)

# Create a SQLAlchemy engine instance using the specified database URL. The echo parameter is set to True, which enables logging of all SQL statements generated by SQLAlchemy, useful for debugging and development purposes.
engine = create_engine(
    Database_URL,
    echo=True,
)

# Define a base class for declarative class definitions using SQLAlchemy's DeclarativeBase. This base class will be used to define the database models (tables) in the application.
SessionLocal = sessionmaker(
    bind=engine,
    autoFlush=False,
    autocommit=False,
)


# Define a base class for declarative class definitions using SQLAlchemy's DeclarativeBase. This base class will be used to define the database models (tables) in the application.
class Base(DeclarativeBase):
    """Base class for declarative class definitions."""
    pass

# Define a dependency function to get a database session. This function creates a new session using the SessionLocal factory, yields it for use in the application, and ensures that the session is closed after use to prevent resource leaks.
def get_db():
    """Dependency function to get a database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()